CREATE DATABASE IF NOT EXISTS RISK_LENS_DB;

USE DATABASE RISK_LENS_DB;

CREATE SCHEMA IF NOT EXISTS RISK_LENS_SCHEMA;

USE SCHEMA RISK_LENS_SCHEMA;

CREATE WAREHOUSE IF NOT EXISTS RISK_LENS_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE RISK_LENS_WH;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CUSTOMER_TYPE VARCHAR(30),
    HOME_CITY VARCHAR(50),
    ACCOUNT_OPEN_DATE DATE,
    RISK_PROFILE VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CUSTOMERS (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_TYPE,
    HOME_CITY,
    ACCOUNT_OPEN_DATE,
    RISK_PROFILE
)
VALUES
    ('CUST001', 'Aarav Sharma', 'Individual', 'Lucknow', '2024-03-15', 'Low'),
    ('CUST002', 'Meera Verma', 'Individual', 'Delhi', '2023-08-21', 'Medium'),
    ('CUST003', 'Demo Business One', 'Business', 'Mumbai', '2022-11-10', 'High');