USE DATABASE RISK_LENS_DB;

USE SCHEMA RISK_LENS_SCHEMA;

USE WAREHOUSE RISK_LENS_WH;

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    ACCOUNT_TYPE VARCHAR(30),
    CURRENT_BALANCE NUMBER(15, 2),
    ACCOUNT_STATUS VARCHAR(20),
    OPEN_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS MERCHANTS (
    MERCHANT_ID VARCHAR(20) PRIMARY KEY,
    MERCHANT_NAME VARCHAR(100),
    MERCHANT_CATEGORY VARCHAR(50),
    MERCHANT_CITY VARCHAR(50),
    MERCHANT_RISK_LEVEL VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID VARCHAR(20) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(20) NOT NULL,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    AMOUNT NUMBER(15, 2),
    TRANSACTION_TYPE VARCHAR(30),
    MERCHANT_ID VARCHAR(20),
    LOCATION VARCHAR(50),
    DEVICE_ID VARCHAR(50),
    STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RISK_RULES (
    RULE_ID VARCHAR(20) PRIMARY KEY,
    RULE_NAME VARCHAR(100),
    RULE_DESCRIPTION VARCHAR(500),
    RISK_WEIGHT NUMBER(5, 2),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ALERTS (
    ALERT_ID VARCHAR(20) PRIMARY KEY,
    TRANSACTION_ID VARCHAR(20) NOT NULL,
    RISK_SCORE NUMBER(5, 2),
    RISK_LEVEL VARCHAR(20),
    TRIGGERED_RULES VARCHAR(1000),
    ALERT_STATUS VARCHAR(30),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS INVESTIGATIONS (
    INVESTIGATION_ID VARCHAR(20) PRIMARY KEY,
    ALERT_ID VARCHAR(20) NOT NULL,
    INVESTIGATOR_NOTE VARCHAR(2000),
    RECOMMENDED_ACTION VARCHAR(100),
    INVESTIGATION_STATUS VARCHAR(30),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);